package eu.kanade.tachiyomi.extension.all.mmrcms

private typealias MMRSource = MyMangaReaderCMSSource

// GENERATED FILE, DO NOT MODIFY!
// Generated on Sat Sep 16 18:41:35 EDT 2017

val SOURCES = mutableListOf<MMRSource>().apply {
    // Read Comics Online
    this += MMRSource(
            "en",
            "Read Comics Online",
            "http://readcomics.website",
            "http://readcomics.website/comic/",
            mutableListOf<Pair<String, String>>().apply {
                this += Pair("17", "One Shots &amp; TPBs")
                this += Pair("33", "DC Comics")
                this += Pair("34", "Marvel Comics")
                this += Pair("35", "Boom Studios")
                this += Pair("36", "Dynamite")
                this += Pair("37", "Rebellion")
                this += Pair("38", "Dark Horse")
                this += Pair("39", "IDW")
                this += Pair("40", "Archie")
                this += Pair("41", "Graphic India")
                this += Pair("42", "Darby Pop")
                this += Pair("43", "Oni Press")
                this += Pair("44", "Icon Comics")
                this += Pair("45", "United Plankton")
                this += Pair("46", "Udon")
                this += Pair("47", "Image Comics")
                this += Pair("48", "Valiant")
                this += Pair("49", "Vertigo")
                this += Pair("50", "Devils Due")
                this += Pair("51", "Aftershock Comics")
                this += Pair("52", "Antartic Press")
                this += Pair("53", "Action Lab")
                this += Pair("54", "American Mythology")
                this += Pair("55", "Zenescope")
                this += Pair("56", "Top Cow")
                this += Pair("57", "Hermes Press")
                this += Pair("58", "451")
                this += Pair("59", "Black Mask")
                this += Pair("60", "Chapterhouse Comics")
                this += Pair("61", "Red 5")
                this += Pair("62", "Heavy Metal")
                this += Pair("63", "Bongo")
                this += Pair("64", "Top Shelf")
                this += Pair("65", "Bubble")
                this += Pair("66", "Boundless")
                this += Pair("67", "Avatar Press")
                this += Pair("68", "Space Goat Productions")
                this += Pair("69", "BroadSword Comics")
                this += Pair("70", "AAM-Markosia")
                this += Pair("71", "Fantagraphics")
                this += Pair("72", "Aspen")
                this += Pair("73", "American Gothic Press")
                this += Pair("74", "Vault")
                this += Pair("75", "215 Ink")
                this += Pair("76", "Abstract Studio")
                this += Pair("77", "Albatross")
                this += Pair("78", "ARH Comix")
                this += Pair("79", "Legendary Comics")
                this += Pair("80", "Monkeybrain")
                this += Pair("81", "Joe Books")
                this += Pair("82", "MAD")
                this += Pair("83", "Comics Experience")
                this += Pair("84", "Alterna Comics")
                this += Pair("85", "Lion Force")
                this += Pair("86", "Benitez")
                this += Pair("87", "Storm King")
                this += Pair("88", "Sucker")
            }
    )
    // Fallen Angels Scans
    this += MMRSource(
            "en",
            "Fallen Angels Scans",
            "http://manga.fascans.com",
            "http://manga.fascans.com/manga/",
            mutableListOf<Pair<String, String>>().apply {
                this += Pair("1", "Action")
                this += Pair("2", "Adventure")
                this += Pair("3", "Comedy")
                this += Pair("4", "Doujinshi")
                this += Pair("5", "Drama")
                this += Pair("6", "Ecchi")
                this += Pair("7", "Fantasy")
                this += Pair("8", "Gender Bender")
                this += Pair("9", "Harem")
                this += Pair("10", "Historical")
                this += Pair("11", "Horror")
                this += Pair("12", "Josei")
                this += Pair("13", "Martial Arts")
                this += Pair("14", "Mature")
                this += Pair("15", "Mecha")
                this += Pair("16", "Mystery")
                this += Pair("17", "One Shot")
                this += Pair("18", "Psychological")
                this += Pair("19", "Romance")
                this += Pair("20", "School Life")
                this += Pair("21", "Sci-fi")
                this += Pair("22", "Seinen")
                this += Pair("23", "Shoujo")
                this += Pair("24", "Shoujo Ai")
                this += Pair("25", "Shounen")
                this += Pair("26", "Shounen Ai")
                this += Pair("27", "Slice of Life")
                this += Pair("28", "Sports")
                this += Pair("29", "Supernatural")
                this += Pair("30", "Tragedy")
                this += Pair("31", "Yaoi")
                this += Pair("32", "Yuri")
                this += Pair("33", "4-Koma")
                this += Pair("34", "Cooking")
            }
    )
    // MangaRoot
    this += MMRSource(
            "en",
            "MangaRoot",
            "http://mangaroot.com",
            "http://mangaroot.com/manga/",
            mutableListOf<Pair<String, String>>().apply {
                this += Pair("1", "Action")
                this += Pair("2", "Adventure")
                this += Pair("3", "Comedy")
                this += Pair("4", "Doujinshi")
                this += Pair("5", "Drama")
                this += Pair("6", "Ecchi")
                this += Pair("7", "Fantasy")
                this += Pair("8", "Gender Bender")
                this += Pair("9", "Harem")
                this += Pair("10", "Historical")
                this += Pair("11", "Horror")
                this += Pair("12", "Josei")
                this += Pair("13", "Martial Arts")
                this += Pair("14", "Mature")
                this += Pair("15", "Mecha")
                this += Pair("16", "Mystery")
                this += Pair("17", "One Shot")
                this += Pair("18", "Psychological")
                this += Pair("19", "Romance")
                this += Pair("20", "School Life")
                this += Pair("21", "Sci-fi")
                this += Pair("22", "Seinen")
                this += Pair("23", "Shoujo")
                this += Pair("24", "Shoujo Ai")
                this += Pair("25", "Shounen")
                this += Pair("26", "Shounen Ai")
                this += Pair("27", "Slice of Life")
                this += Pair("28", "Sports")
                this += Pair("29", "Supernatural")
                this += Pair("30", "Tragedy")
                this += Pair("31", "Yaoi")
                this += Pair("32", "Yuri")
                this += Pair("33", "Webtoon")
            }
    )
    // Mangawww Reader
    this += MMRSource(
            "en",
            "Mangawww Reader",
            "http://mangawww.com",
            "http://mangawww.com/manga/",
            mutableListOf<Pair<String, String>>().apply {
                this += Pair("1", "Action")
                this += Pair("2", "Adventure")
                this += Pair("3", "Comedy")
                this += Pair("4", "Doujinshi")
                this += Pair("5", "Drama")
                this += Pair("6", "Ecchi")
                this += Pair("7", "Fantasy")
                this += Pair("8", "Gender Bender")
                this += Pair("9", "Harem")
                this += Pair("10", "Historical")
                this += Pair("11", "Horror")
                this += Pair("12", "Josei")
                this += Pair("13", "Martial Arts")
                this += Pair("14", "Mature")
                this += Pair("15", "Mecha")
                this += Pair("16", "Mystery")
                this += Pair("17", "One Shot")
                this += Pair("18", "Psychological")
                this += Pair("19", "Romance")
                this += Pair("20", "School Life")
                this += Pair("21", "Sci-fi")
                this += Pair("22", "Seinen")
                this += Pair("23", "Shoujo")
                this += Pair("24", "Shoujo Ai")
                this += Pair("25", "Shounen")
                this += Pair("26", "Shounen Ai")
                this += Pair("27", "Slice of Life")
                this += Pair("28", "Sports")
                this += Pair("29", "Supernatural")
                this += Pair("30", "Tragedy")
                this += Pair("31", "Yaoi")
                this += Pair("32", "Yuri")
            }
    )
    // MangaForLife
    this += MMRSource(
            "en",
            "MangaForLife",
            "http://manga4ever.com",
            "http://manga4ever.com/manga/",
            mutableListOf<Pair<String, String>>().apply {
                this += Pair("1", "Action")
                this += Pair("2", "Adventure")
                this += Pair("3", "Comedy")
                this += Pair("4", "Doujinshi")
                this += Pair("5", "Drama")
                this += Pair("6", "Ecchi")
                this += Pair("7", "Fantasy")
                this += Pair("8", "Gender Bender")
                this += Pair("9", "Harem")
                this += Pair("10", "Historical")
                this += Pair("11", "Horror")
                this += Pair("12", "Josei")
                this += Pair("13", "Martial Arts")
                this += Pair("14", "Mature")
                this += Pair("15", "Mecha")
                this += Pair("16", "Mystery")
                this += Pair("17", "One Shot")
                this += Pair("18", "Psychological")
                this += Pair("19", "Romance")
                this += Pair("20", "School Life")
                this += Pair("21", "Sci-fi")
                this += Pair("22", "Seinen")
                this += Pair("23", "Shoujo")
                this += Pair("24", "Shoujo Ai")
                this += Pair("25", "Shounen")
                this += Pair("26", "Shounen Ai")
                this += Pair("27", "Slice of Life")
                this += Pair("28", "Sports")
                this += Pair("29", "Supernatural")
                this += Pair("30", "Tragedy")
                this += Pair("31", "Yaoi")
                this += Pair("32", "Yuri")
            }
    )
    // My-mangas.com
    this += MMRSource(
            "es",
            "My-mangas.com",
            "https://my-mangas.com",
            "https://my-mangas.com/manga/",
            mutableListOf<Pair<String, String>>().apply {
                this += Pair("1", "Acción")
                this += Pair("2", "Aventura")
                this += Pair("3", "Comedia")
                this += Pair("4", "Doujinshi")
                this += Pair("5", "Drama")
                this += Pair("6", "Ecchi")
                this += Pair("7", "Fantasía")
                this += Pair("8", "Gender Bender")
                this += Pair("9", "Harem")
                this += Pair("10", "Histórico")
                this += Pair("11", "Horror")
                this += Pair("12", "Josei")
                this += Pair("13", "Artes Marciales")
                this += Pair("14", "Maduro")
                this += Pair("15", "Mecha")
                this += Pair("16", "Misterio")
                this += Pair("17", "One Shot")
                this += Pair("18", "Psicológico")
                this += Pair("19", "Romance")
                this += Pair("20", "Escolar")
                this += Pair("21", "Ciencia Ficción")
                this += Pair("22", "Seinen")
                this += Pair("23", "Shoujo")
                this += Pair("24", "Shoujo Ai")
                this += Pair("25", "Shounen")
                this += Pair("26", "Shounen Ai")
                this += Pair("27", "Recuentos de la vida")
                this += Pair("28", "Deportes")
                this += Pair("29", "Supernatural")
                this += Pair("30", "Tragedia")
                this += Pair("31", "Yaoi")
                this += Pair("32", "Yuri")
                this += Pair("33", "Demonios")
                this += Pair("34", "Juegos")
                this += Pair("35", "Policial")
                this += Pair("36", "Militar")
                this += Pair("37", "Thriller")
                this += Pair("38", "Autos")
                this += Pair("39", "Música")
                this += Pair("40", "Vampiros")
                this += Pair("41", "Magia")
                this += Pair("42", "Samurai")
            }
    )
    // TrinityReader
    this += MMRSource(
            "fa",
            "TrinityReader",
            "http://trinityreader.pw",
            "http://trinityreader.pw/manga/",
            mutableListOf<Pair<String, String>>().apply {
                this += Pair("1", "Action")
                this += Pair("2", "Adventure")
                this += Pair("3", "Comedy")
                this += Pair("4", "Doujinshi")
                this += Pair("5", "Drama")
                this += Pair("6", "Ecchi")
                this += Pair("7", "Fantasy")
                this += Pair("8", "Gender Bender")
                this += Pair("9", "Harem")
                this += Pair("10", "Historical")
                this += Pair("11", "Horror")
                this += Pair("12", "Josei")
                this += Pair("13", "Martial Arts")
                this += Pair("14", "Mature")
                this += Pair("15", "Mecha")
                this += Pair("16", "Mystery")
                this += Pair("17", "One Shot")
                this += Pair("18", "Psychological")
                this += Pair("19", "Romance")
                this += Pair("20", "School Life")
                this += Pair("21", "Sci-fi")
                this += Pair("22", "Seinen")
                this += Pair("23", "Shoujo")
                this += Pair("24", "Shoujo Ai")
                this += Pair("25", "Shounen")
                this += Pair("26", "Shounen Ai")
                this += Pair("27", "Slice of Life")
                this += Pair("28", "Sports")
                this += Pair("29", "Supernatural")
                this += Pair("30", "Tragedy")
                this += Pair("31", "Yaoi")
                this += Pair("32", "Yuri")
            }
    )
    // Manga Desu
    this += MMRSource(
            "id",
            "Manga Desu",
            "http://mangadesu.net",
            "http://mangadesu.net/manga/",
            mutableListOf<Pair<String, String>>().apply {
                this += Pair("1", "Action")
                this += Pair("2", "Adventure")
                this += Pair("3", "Comedy")
                this += Pair("4", "Doujinshi")
                this += Pair("5", "Drama")
                this += Pair("6", "Ecchi")
                this += Pair("7", "Fantasy")
                this += Pair("8", "Gender Bender")
                this += Pair("9", "Harem")
                this += Pair("10", "Historical")
                this += Pair("11", "Horror")
                this += Pair("12", "Josei")
                this += Pair("13", "Martial Arts")
                this += Pair("14", "Mature")
                this += Pair("15", "Mecha")
                this += Pair("16", "Mystery")
                this += Pair("17", "One Shot")
                this += Pair("18", "Psychological")
                this += Pair("19", "Romance")
                this += Pair("20", "School Life")
                this += Pair("21", "Sci-fi")
                this += Pair("22", "Seinen")
                this += Pair("23", "Shoujo")
                this += Pair("24", "Shoujo Ai")
                this += Pair("25", "Shounen")
                this += Pair("26", "Shounen Ai")
                this += Pair("27", "Slice of Life")
                this += Pair("28", "Sports")
                this += Pair("29", "Supernatural")
                this += Pair("30", "Tragedy")
                this += Pair("31", "Yaoi")
                this += Pair("32", "Yuri")
                this += Pair("33", "Magic")
                this += Pair("34", "Super Power")
                this += Pair("35", "Demons")
                this += Pair("36", "Isekai")
            }
    )
    // IchigoBook
    this += MMRSource(
            "ja",
            "IchigoBook",
            "http://ichigobook.com",
            "http://ichigobook.com/manga/",
            mutableListOf<Pair<String, String>>().apply {
                this += Pair("1", "Action")
                this += Pair("2", "Adventure")
                this += Pair("3", "Comedy")
                this += Pair("4", "Doujinshi")
                this += Pair("5", "Drama")
                this += Pair("6", "Ecchi")
                this += Pair("7", "Fantasy")
                this += Pair("8", "Gender Bender")
                this += Pair("9", "Harem")
                this += Pair("10", "Historical")
                this += Pair("11", "Horror")
                this += Pair("12", "Josei")
                this += Pair("13", "Martial Arts")
                this += Pair("14", "Mature")
                this += Pair("15", "Mecha")
                this += Pair("16", "Mystery")
                this += Pair("17", "One Shot")
                this += Pair("18", "Psychological")
                this += Pair("19", "Romance")
                this += Pair("20", "School Life")
                this += Pair("21", "Sci-fi")
                this += Pair("22", "Seinen")
                this += Pair("23", "Shoujo")
                this += Pair("24", "Shoujo Ai")
                this += Pair("25", "Shounen")
                this += Pair("26", "Shounen Ai")
                this += Pair("27", "Slice of Life")
                this += Pair("28", "Sports")
                this += Pair("29", "Supernatural")
                this += Pair("30", "Tragedy")
                this += Pair("31", "Yaoi")
                this += Pair("32", "Yuri")
                this += Pair("33", "Adult")
                this += Pair("34", "音楽")
                this += Pair("35", "雑誌")
            }
    )
    // MangAoi
    this += MMRSource(
            "tr",
            "MangAoi",
            "http://mangaoi.com",
            "http://mangaoi.com/manga/",
            mutableListOf<Pair<String, String>>().apply {
                this += Pair("1", "Action")
                this += Pair("2", "Adventure")
                this += Pair("3", "Comedy")
                this += Pair("4", "Doujinshi")
                this += Pair("5", "Drama")
                this += Pair("6", "Ecchi")
                this += Pair("7", "Fantasy")
                this += Pair("8", "Gender Bender")
                this += Pair("9", "Harem")
                this += Pair("10", "Historical")
                this += Pair("11", "Horror")
                this += Pair("12", "Josei")
                this += Pair("13", "Martial Arts")
                this += Pair("14", "Mature")
                this += Pair("15", "Mecha")
                this += Pair("16", "Mystery")
                this += Pair("17", "One Shot")
                this += Pair("18", "Psychological")
                this += Pair("19", "Romance")
                this += Pair("20", "School Life")
                this += Pair("21", "Sci-fi")
                this += Pair("22", "Seinen")
                this += Pair("23", "Shoujo")
                this += Pair("24", "Shoujo Ai")
                this += Pair("25", "Shounen")
                this += Pair("26", "Shounen Ai")
                this += Pair("27", "Slice of Life")
                this += Pair("28", "Sports")
                this += Pair("29", "Supernatural")
                this += Pair("30", "Tragedy")
                this += Pair("31", "Yaoi")
                this += Pair("32", "Yuri")
            }
    )
}
